name: linux

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test ${{matrix.build-type}} mode
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Clone recursively
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install newest g++, valgrind
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install g++-14 valgrind
          export CXX=g++-14

      - name: Configure
        run: CXX=g++-14 cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build -v

      - name: Test
        run: bash test/run_tests.sh ${{github.workspace}}/build/bin/let

      - name: Test with Valgrind
        run: valgrind --error-exitcode=1 --leak-check=full ${{github.workspace}}/build/bin/let ${{github.workspace}}/test/eval.let -e

  sanitize:
    name: ASan+LSan+UBSan
    runs-on: ubuntu-latest

    steps:
      - name: Clone recursively
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install newest g++
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install g++-14

      - name: Configure
        run: >
          CXX=g++-14 cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_FLAGS="-fsanitize=address,leak,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
          -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,leak,undefined"

      - name: Build
        run: cmake --build ${{github.workspace}}/build -v

      - name: Test
        run: bash test/run_tests.sh ${{github.workspace}}/build/bin/let
        env:
          ASAN_OPTIONS: detect_leaks=1
          UBSAN_OPTIONS: print_stacktrace=1
