name: linux

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test ${{matrix.build-type}} mode
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Clone recursively
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install newest g++, valgrind
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install g++-13 valgrind
          export CXX=g++-13

      - name: Configure
        run: CXX=g++-13 cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build -v

      - name: Test with Valgrind
        run: valgrind --error-exitcode=1 --leak-check=full ${{github.workspace}}/build/bin/let ${{github.workspace}}/test/test.let
